services:
  app:
    build: ./src
    container_name: minichat-app
    restart: on-failure
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: minichat-db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
